pluginManagement {
    plugins {
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorConvertVersion}"
        id 'io.spring.javaformat' version "${springJavaFormatVersion}"
    }
}

rootProject.name = 'matdongsan-server'

include 'core'
include 'support'
include 'support:logging'
findProject(':support:logging')?.name = 'logging'
include 'support:monitoring'
findProject(':support:monitoring')?.name = 'monitoring'

