pluginManagement {
    plugins {
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorConvertVersion}"
        id 'io.spring.javaformat' version "${springJavaFormatVersion}"
    }
}

rootProject.name = 'matdongsan-server'

include 'core'
include 'support'
include 'support:logging'
findProject(':support:logging')?.name = 'logging'
include 'support:monitoring'
findProject(':support:monitoring')?.name = 'monitoring'
include 'clients'
include 'clients:openai-client'
findProject(':clients:openai-client')?.name = 'openai-client'
include 'clients:kakao-client'
findProject(':clients:kakao-client')?.name = 'kakao-client'
include 'clients:tts-client'
findProject(':clients:tts-client')?.name = 'tts-client'

